  spring:
    application:
      name: user-service
    profiles:
      active: development
---
server:
  port: 8181
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/login-system
    username: loginuser
    password: loginpass
security:
  oauth2:
    resource:
      filter-order: 3
flyway:
  table: users_schema_version
  baseline-on-migrate: true
---
spring:
  profiles: test
  jpa:
    generate-ddl: true
    hibernate-ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:user-test;DB_CLOSE_DELAY=-1
    username: sa
  cloud:
    discovery:
      enabled: false
security:
  user:
    name: user
    password: password