spring:
  profiles:
    active: development
---
server:
  port: 8182
spring:
  profiles: development
  application:
    name: profile-service
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:profile-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
security:
  user:
    name: user
    password: password