spring:
  application:
    name: profile-service
  profiles:
    active: development
---
server:
  port: 8182
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/login-system
    username: loginuser
    password: loginpass
  oauth2:
    client:
      client-id: webClient
      client-secret: secret
      access-token-uri: http://localhost:8182/oauth/access_token
      user-authorization-uri: http://localhost:8182/oauth/authorize
      grant-type: password
    resource:
      jwt:
        key-value: 45eebbdae9b69253cd56744330384d8bb7d38bb40b9d1a1cfa5b29b3c73d4c46
        filter-order: 3
---
server:
  port: 8182
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:profile-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
security:
  user:
    name: user
    password: password
  oauth2:
    client:
      client-id: webClient
      client-secret: secret
      access-token-uri: http://localhost:8182/oauth/access_token
      user-authorization-uri: http://localhost:8182/oauth/authorize
    resource:
      jwt:
        key-value: 45eebbdae9b69253cd56744330384d8bb7d38bb40b9d1a1cfa5b29b3c73d4c46
        filter-order: 3